version: '3.3'
services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5555:5432'
    volumes:
      - my-db:/var/lib/postgresql


volumes:
  my-db:
